name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install fastapi uvicorn requests pytest httpx

    - name: Run tests
      run: |
        pytest .github/ --maxfail=1 --disable-warnings -q

    - name: Lint code
      run: |
        pip install pylint
        pylint app.py
